## Cosine Similarity Calculations
Cosine similarity is a measure of similarity between two non-zero vectors of an inner product space that measures the cosine of the angle between them. Similarity measures have a multiude of uses in machine learning projects; they come in handy when matching strings, measuring distance, and extracting features. This similarity measurement is particularly concerned with orientation, rather than magnitude. 
In this case study, you'll use the cosine similarity to compare both a numeric data within a plane and a text dataset for string matching.

Load the Python modules, including cosine_similarity, from sklearn.metrics.pairwise

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
%matplotlib inline
plt.style.use('ggplot')
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity

**<font color='teal'> Load the distance dataset into a dataframe. </font>**

In [5]:
distance=pd.read_csv('C:/Users/gellima/Desktop/Springboard_DScience/CosineSimilarityCaseStudy/distance_dataset (1).csv')
distance.head()


Unnamed: 0         X         Y         Z  ClusterID
0           0  5.135779  4.167542  5.787635          4
1           1  4.280721  5.770909  6.091044          4
2           2  8.329098  7.540436  3.247239          2
3           3  5.470224  5.069249  5.768313          4
4           4  2.381797  2.402374  3.879101          1

### Cosine Similarity with clusters and numeric matrices

All points in our dataset can be thought of as feature vectors. We illustrate it here as we display the __Cosine Similarity__ between each feature vector in the YZ plane and the [5, 5] vector we chose as reference. The sklearn.metrics.pairwise module provides an efficient way to compute the __cosine_similarity__ for large arrays from which we can compute the similarity.

 **<font color='teal'> First, create a 2D and a 3D matrix from the dataframe. The 2D matrix should contain the 'Y' and 'Z' columns and the 3D matrix should contain the 'X','Y', and 'Z' columns.</font>**

In [14]:
two_matrix=np.array(distance[['Y','Z']])
two_matrix


array([[4.16754224, 5.7876354 ],
       [5.77090875, 6.0910442 ],
       [7.54043595, 3.2472394 ],
       ...,
       [2.35191142, 6.77931097],
       [5.64267723, 4.85577967],
       [5.27055029, 7.84476766]])

In [15]:
two_matrix.shape

(2000, 2)

In [17]:
df1=distance[['X','Y','Z']]
df1.head()

X         Y         Z
0  5.135779  4.167542  5.787635
1  4.280721  5.770909  6.091044
2  8.329098  7.540436  3.247239
3  5.470224  5.069249  5.768313
4  2.381797  2.402374  3.879101

In [19]:
df1.shape

(2000, 3)

In [18]:
arr = df1.to_numpy().reshape(5,5,5)

ValueError: cannot reshape array of size 6000 into shape (5,5,5)

In [16]:
three_matrix.shape

(2000, 3)

Calculate the cosine similarity for those matrices with reference planes of 5,5 and 5,5,5. Then subtract those measures from 1 in new features.

In [12]:
simCosine3D = 1. - cosine_similarity(mat, [[5,5,5]], 'cosine')
simCosine = 1. - cosine_similarity(matYZ, [[5,5]], 'cosine')

NameError: name 'mat' is not defined

Using the 2D matrix and the reference plane of (5,5) we can use a scatter plot to view the way the similarity is calculated using the Cosine angle.

In [0]:
figCosine = plt.figure(figsize=[10,8])

plt.scatter(df.Y, df.Z, c=simCosine[:,0], s=20)
plt.plot([0,5],[0,5], '--', color='dimgray')
plt.plot([0,3],[0,7.2], '--', color='dimgray')
plt.text(0.7,2.6,r'$\theta$ = 22.4 deg.', rotation=47, size=14)
plt.ylim([0,10])
plt.xlim([0,10])
plt.xlabel('Y', size=14)
plt.ylabel('Z', size=14)
plt.title('Cosine Similarity')
cb = plt.colorbar()
cb.set_label('Similarity with (5,5)', size=14)

#figCosine.savefig('similarity-cosine.png')

Now, plot the 3D matrix with the similarity and the reference plane, (5,5,5).

In [0]:
from mpl_toolkits.mplot3d import Axes3D
figCosine3D = plt.figure(figsize=(10, 8))
ax = figCosine3D.add_subplot(111, projection='3d')

p = ax.scatter(mat[:,0], mat[:,1], mat[:,2], c=simCosine3D[:,0])
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
cb = figCosine3D.colorbar(p)
cb.set_label('Similarity with (5,5,5)', size=14)
                                   
figCosine3D.tight_layout()
#figCosine3D.savefig('cosine-3D.png', dpi=300, transparent=True)

----

### Cosine Similarity with text data
This is a quick example of how you can use Cosine Similarity to compare different text values or names for record matching or other natural language proecessing needs. 
First, we use count vectorizer to create a vector for each unique word in our Document 0 and Document 1. 

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
Document1 = "Starbucks Coffee"
Document2 = "Essence of Coffee"

corpus = [Document1,Document2]

X_train_counts = count_vect.fit_transform(corpus)

pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 0','Document 1'])

coffee  essence  of  starbucks
Document 0       1        0   0          1
Document 1       1        1   1          0

Now, we use a common frequency tool called TF-IDF to convert the vectors to unique measures.

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
trsfm=vectorizer.fit_transform(corpus)
pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 0','Document 1'])

coffee   essence        of  starbucks
Document 0  0.579739  0.000000  0.000000   0.814802
Document 1  0.449436  0.631667  0.631667   0.000000

Here, we finally apply the __Cosine Similarity__ measure to calculate how similar Document 0 is compared to any other document in the corpus. Therefore, the first value of 1 is showing that the Document 0 is 100% similar to Document 0 and 0.26055576 is the similarity measure between Document 0 and Document 1.

In [22]:
# cosine similarity with TfidfVectorizer
cosine_similarity(trsfm[0:1], trsfm)

array([[1.        , 0.26055567]])

In [23]:
# cosine similarity with CountVectorizer
cosine_similarity(X_train_counts[0:1],X_train_counts)

array([[1.        , 0.40824829]])

Replace the current values for `Document 0` and `Document 1` with your own sentence or paragraph and apply the same steps as we did in the above example.

 **<font color='teal'> Combine the documents into a corpus.</font>**

In [25]:
Document0='Malli is taking Data Science Boot camp, is from June 1st cohort session. She is very curious person, learns data science skills in interactive mode'
Document1='Nihil is Data Science Boot camp student from August 1st cohort session. He learns and applies data science skills very diligently across various projects for his career'
corpus=[Document0, Document1]
corpus

['Malli is taking Data Science Boot camp, is from June 1st cohort session. She is very curious person, learns data science skills in interactive mode',
 'Nihil is Data Science Boot camp student from August 1st cohort session. He learns and applies data science skills very diligently across various projects for his career']

 **<font color='teal'> Apply the count vectorizer to the corpus to transform it into vectors.</font>**

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer()
data_vectors=count_vect.fit_transform(corpus)

 **<font color='teal'> Convert the vector counts to a dataframe with Pandas.</font>**

In [30]:
pd.DataFrame(data_vectors.toarray(), columns=count_vect.get_feature_names(), index=['Student1', 'Student2'])

1st  across  and  applies  august  boot  camp  career  cohort  \
Student1    1       0    0        0       0     1     1       0       1   
Student2    1       1    1        1       1     1     1       1       1   

          curious  ...  person  projects  science  session  she  skills  \
Student1        1  ...       1         0        2        1    1       1   
Student2        0  ...       0         1        2        1    0       1   

          student  taking  various  very  
Student1        0       1        0     1  
Student2        1       0        1     1  

[2 rows x 34 columns]

 **<font color='teal'> Apply TF-IDF to convert the vectors to unique frequency measures.</font>**

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
tdif=TfidfVectorizer()
tfdata=tdif.fit_transform(corpus)
pd.DataFrame(tfdata.toarray(), columns=tdif.get_feature_names(), index=['Student1', 'Student2'])

1st    across       and   applies    august      boot  \
Student1  0.151137  0.000000  0.000000  0.000000  0.000000  0.151137   
Student2  0.151308  0.212658  0.212658  0.212658  0.212658  0.151308   

              camp    career    cohort   curious  ...    person  projects  \
Student1  0.151137  0.000000  0.151137  0.212418  ...  0.212418  0.000000   
Student2  0.151308  0.212658  0.151308  0.000000  ...  0.000000  0.212658   

           science   session       she    skills   student    taking  \
Student1  0.302275  0.151137  0.212418  0.151137  0.000000  0.212418   
Student2  0.302616  0.151308  0.000000  0.151308  0.212658  0.000000   

           various      very  
Student1  0.000000  0.151137  
Student2  0.212658  0.151308  

[2 rows x 34 columns]

 **<font color='teal'> Use the cosine similarity function to get measures of similarity for the sentences or paragraphs in your original document.</font>**

In [37]:
# cosine similarity between two documents using CountVectorizer
cosine_similarity(data_vectors)

array([[1.        , 0.60717674],
       [0.60717674, 1.        ]])

In [38]:
# cosine similarity between two documents using TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(tfdata)

array([[1.       , 0.4573663],
       [0.4573663, 1.       ]])